# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - onlineweb-frontend

on:
  push:
    branches:
      - azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Prepeare deployment folder
        run: mkdir -p deployment_build

      - name: npm install
        run: npm install

      - name: NPM build
        run: npm run build

      - name: Upload package.json
      - uses: actions/upload-artifact@v2
        with:
          name: deployment_build
          path: package.json

      - name: Move build files
        run: mv .next deployment_build
      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          name: deployment_build
          path: deployment_build/.next

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "onlineweb-frontend"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e04e52940ded45e3afdf32dfab711104 }}
          package: deployment_build
