name: Continuous Deployment

on:
  push:
    branches:
      - azure
  # release:
  # types: [published, edited]

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push to Azure Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY }}/onlineweb-frontend:latest
      - uses: azure/webapps-deploy@v2
        with:
          app-name: "onlineweb-frontend"
          slot-name: "production"
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          images: "${{ secrets.CONTAINER_REGISTRY }}/onlineweb-frontend:latest"
